"""
Centralized Configuration for CardioPulse ML Pipeline.
Supports runtime configuration via environment variables with zero hardcoded machine-specific paths.
"""

import os
from pathlib import Path

# Base repository root directory
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Configurable paths with environment variable overrides
DATASET_PATH = Path(os.getenv("ML_DATASET_PATH", PROJECT_ROOT / "data" / "dataset.csv"))
ARTIFACT_DIR = Path(os.getenv("ML_ARTIFACT_DIR", PROJECT_ROOT / "ml" / "artifacts"))
MODEL_PATH = Path(os.getenv("ML_MODEL_PATH", ARTIFACT_DIR / "model.joblib"))
METADATA_PATH = Path(os.getenv("ML_METADATA_PATH", ARTIFACT_DIR / "model_metadata.json"))
REGISTRY_PATH = Path(os.getenv("ML_REGISTRY_PATH", ARTIFACT_DIR / "model_registry.json"))
OUTPUT_DIR = Path(os.getenv("ML_OUTPUT_DIR", PROJECT_ROOT / "outputs"))

# Supported Multi-Model Registry IDs
DEFAULT_MODEL_ID = "logistic_regression"
SUPPORTED_MODEL_IDS = ["logistic_regression", "svm", "random_forest", "xgboost"]

# Deterministic reproducible ML configuration
RANDOM_STATE = 42
TEST_SIZE = 0.20
SELECTION_CRITERION = "ROC-AUC"

# Canonical feature schema
CANONICAL_FEATURES = [
    "age",
    "sex",
    "cp",
    "trestbps",
    "chol",
    "fbs",
    "restecg",
    "thalach",
    "exang",
    "oldpeak",
    "slope",
    "ca",
    "thal"
]

NUMERICAL_FEATURES = ["age", "trestbps", "chol", "thalach", "oldpeak"]
CATEGORICAL_FEATURES = ["sex", "cp", "fbs", "restecg", "exang", "slope", "ca", "thal"]

# Strict target leakage prevention exclusions
EXCLUDED_FEATURES = ["num", "target", "id"]

# Production candidate model metadata
PRODUCTION_MODEL_NAME = "Logistic Regression"
PRODUCTION_MODEL_VERSION = "heart-disease-logistic-regression-v1"

# Target labels
TARGET_LABELS = {
    0: "No Heart Disease",
    1: "Presence of Heart Disease"
}

# Educational & research medical disclaimer
EDUCATIONAL_DISCLAIMER = (
    "This project is intended for educational and research purposes only. "
    "The predictions generated by this machine-learning model should not be interpreted "
    "as medical advice, diagnosis, or a substitute for evaluation by a qualified healthcare professional."
)
